name: Run bot
on:
  schedule:
    - cron: '35 19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
        echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
        echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> $GITHUB_ENV
        echo "API_SECRET_KEY=${{ secrets.API_SECRET_KEY }}" >> $GITHUB_ENV

    - name: Run your Python script
      run: |
        python main.py
