name: Run bot
on:
  schedule:
    - cron: '56 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run your Python script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
      run: |
        python main.py
